S05 recaptcha
WildCodeSchool-2024-02/PHP-REM-POEC-05-Gazette-Sorciers pull request #47
Opened 2024-08-01 15:16 UTC by E-mna

2024-08-01 15:20 UTC, Chaimette approved these changes

2024-08-01 16:13 UTC, GuillaumeCregut requested changes

2024-08-01 16:13 UTC, GuillaumeCregut commented on src/Controller/ContactController.php
> +        $secretKey = '6LcfQx0qAAAAAMP8A1QMUrxBZqA64HC33kdXW_n5';
Pas de clés secretes dans le code.
Pour cela il faut utiliser le fichier db.php

2024-08-01 16:13 UTC, GuillaumeCregut commented on src/Controller/UserController.php
> +        $secretKey = '6LcfQx0qAAAAAMP8A1QMUrxBZqA64HC33kdXW_n5';
Pareil

2024-08-01 16:13 UTC, GuillaumeCregut commented on src/View/Auth/register.html.twig
> +        <div class="g-recaptcha" data-sitekey="6LcfQx0qAAAAAMDontxsKVtB4BU6GHXT8oc71ZP5"></div>
Des clés dans le HTML ?

2024-08-01 16:13 UTC, GuillaumeCregut commented on src/View/Contact/_form.html.twig
> +            <div class="g-recaptcha" data-sitekey="6LcfQx0qAAAAAMDontxsKVtB4BU6GHXT8oc71ZP5"></div>
Des clés dans le HTML ?

2024-08-01 16:14 UTC, GuillaumeCregut commented
On va éviter les secrets dans le code.
Par contre, je suis étonné qu'il faille en mettre dans le HTML

2024-08-01 18:34 UTC, E-mna commented
le sitekey doit etre publique pour que le widget recaptcha puisse apparaitre et fonctionner.
c'est une clé de configuration identifie le site au service recaptcha
d'apres ce que j'ai compris  sitekey  n'est pas considérée comme un "secret" dans le même sens que des mots de passe ou des clés

2024-08-02 07:28 UTC, Chaimette approved these changes

2024-08-02 07:43 UTC, GuillaumeCregut approved these changes

2024-08-02 07:43 UTC, merged